# Generated by Django 4.1.5 on 2023-01-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('caption', models.TextField(verbose_name='caption')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('is_public', models.BooleanField(default=True, help_text='Public Ads will be displayed in the api views.', verbose_name='is public')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ('-date_added',),
                'get_latest_by': 'date_added',
            },
        ),
    ]
