# Generated by Django 4.1.5 on 2023-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09916883866', max_length=11, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
